version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chat_application
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build:
      context: ./
    container_name: chat_application_backend
    environment:
      DB_USER: "root"
      DB_PASSWORD: "secret"
      DB_NAME: "chat_application"
      DB_HOST: db
      DB_PORT: "3306"
      TEST_DB_NAME: "chat_application_test"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge